apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: cert-manager
spec:
  commonName: MyCA
  duration: 43800h
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: selfsigned-ca
