---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
  labels:
    app.kubernetes.io/instance: server
    app.kubernetes.io/name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: server
      app.kubernetes.io/name: server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: server
        app.kubernetes.io/name: server
    spec:
      containers:
        - name: server
          image: ghcr.io/mpsoxygen/gunicorn-tls-alpine:latest
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: certs
              mountPath: /app/certs
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 8
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      volumes:
        - name: certs
          secret:
            secretName: server-tls
            defaultMode: 0400 # Readable by owner (app)
            items:
              - key: tls.crt
                path: server.crt
              - key: tls.key
                path: server.key
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 1000 # Ensure mounted volumes have GID 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      schedulerName: default-scheduler

---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
spec:
  ports:
    - name: server-https
      protocol: TCP
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: server
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
