apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-certificates-volume
spec:
  background: false
  rules:
    - name: add-ssl-certs
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: '{{request.object.metadata.annotations."inject-certs" || ""}}'
            operator: Equals
            value: enabled
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
      mutate:
        foreach:
          - list: request.object.spec.containers
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    volumeMounts:
                      - mountPath: /etc/ssl/certs
                        name: etc-ssl-certs
                        readOnly: true
                volumes:
                  - configMap:
                      items:
                        - key: root-certs.pem
                          path: ca-certificates.crt
                      name: example-bundle
                      optional: false
                    name: etc-ssl-certs
